import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';


class WatchData {
  // add in all data that will be generated by ML e.g.
  WatchData({required this.snackingTime});

  final int snackingTime;

  // factory WatchData.fromJSON(Map<String, dynamic> data) { 
  //   return ; 
  // }

}




